### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ow** [lazaronixon/trix-extensions#1]
Hey! Stumbled on this when looking for a way to add a `h2` to the Trix toolbar.... but how do I actually use it?

**Comment by vinyll** [comment]
It seems to be very much Ruby dependant.
Too bad for a js-client tool.

I guess it still shows it's feasible and provides hints.

**Comment by siscia** [comment]
Hum, the code does not seems Ruby dependent to me... Especially since trix just create html on the client and send it to the backend.

I belueve we can definitely work on this...
